<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.18" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.11" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TaskPlatform.Shared\TaskPlatform.Shared.csproj" />
    <ProjectReference Include="..\Modules\UserManagement\UserManagement.csproj" />
    <ProjectReference Include="..\Modules\Authentication\Authentication.csproj" />
    <ProjectReference Include="..\Modules\Workspaces\Workspaces.csproj" />
    <ProjectReference Include="..\Modules\Projects\Projects.csproj" />
    <ProjectReference Include="..\Modules\Tasks\Tasks.csproj" />
    <ProjectReference Include="..\Modules\Collaboration\Collaboration.csproj" />
    <ProjectReference Include="..\Modules\Notifications\Notifications.csproj" />
    <ProjectReference Include="..\Modules\TimeTracking\TimeTracking.csproj" />
  </ItemGroup>

</Project>
